Fix FIFO overflow issue
multi-channel-electronics/arc_pci pull request #1
Opened 2023-01-17 17:44 UTC by mpetroff

These changes check the fiber FIFOs while waiting for response from kernel driver to avoid data corruption due to FIFO overflow. Also introduced is a debugging mode that verifies the MCE data packet checksums in the fiber card firmware, and the version number is bumped to U0108.
    
As the fiber link from the MCE operates at 25&thinsp;MB/s and is fed into a pair of FIFOs that hold 1024 bytes each, the FIFOs fill up in ~80&thinsp;us. Prior to this change, the firmware (when in c7 mode) did not check the FIFOs from when it initiated data transfer of a datagram to the host machine, such as for circular buffer bookkeeping, until after it received confirmation from the host machine that the datagram had been received and processed by the kernel driver. In the worst case, when this process started just prior to data being received over the fiber from the MCE, this meant that the FIFOs would fill up and data would be lost if this process took more than the ~80us it takes for the FIFOs to fill up. With this change, the FIFOs are checked while waiting for the kernel driver, so we are no longer dependent on the kernel driver quickly servicing its interrupt.
    
This issue was discovered after a long and painful debugging process into why a particular hardware setup ([Intel Xeon E-2224G CPU](https://ark.intel.com/content/www/us/en/ark/products/191037/intel-xeon-e2224g-processor-8m-cache-3-50-ghz.html) installed in an [ASRock Rack C246 WS](https://www.asrockrack.com/general/productdetail.asp?Model=C246%20WS) motherboard) had checksum verification failures several times a minute. Even when running off identical disk images and with the fiber card installed in an external PCI-to-PCIe chassis such that there were identical electrical connections to the fiber card, this computer would experience data corruption while there would be no issues with the old computer that was being replaced. For unclear reasons, the problematic computer seems to take longer to initiate PCI transactions. After this fix was shown to work, the root cause was verified by soldering a wire to the full flag pin (pin 9) on one of the FIFO chips (U14) on a fiber card running unmodified U0107 firmware and monitoring it with an oscilloscope. Sure enough, this showed that the full flag was asserted on order 100&thinsp;us every few seconds and that this was the cause of the data corruption. While this problematic hardware surfaced the issue that was fixed, it may very well have caused data corruption on other hardware with less regularity.

A data packet checksum verification mode was also added. When enabled by setting a new `MODE_VERIFY_CHECKSUM` bit in `MODE`, the fiber FIFOs are emptied by a new subroutine, which verifies the data packet checksums and increments an error count in `CHECKSUM_FAILS`. As it is slower than the default subroutine, it should only be enabled for debugging purposes. This subroutine proved very useful in debugging the above issue.

2023-01-18 01:42 UTC, mhasself requested changes
As discussed in email -- thanks for submitting these improvements and tagging the new version.

One comment on the code.

2023-01-18 01:42 UTC, mhasself commented on src/comms7.asm
> +	JEQ	CHECK_FOR_DATA__BUFFER__CHECKSUM__EXIT
I think this logic isn't quite right.  For example, if A=1 and B=0, it passes the test.  It will catch B!=0 correctly, as long as B!=A ...

2023-01-18 21:21 UTC, mpetroff commented on src/comms7.asm
> +	JEQ	CHECK_FOR_DATA__BUFFER__CHECKSUM__EXIT
Yes, it's wrong. I originally tried to clear `X0` and compare both `A` and `B` to that, just to get an assembler error because the `CMP` instruction didn't work with `X0`, and I made a mistake when avoiding using other registers. As it caught all the checksum failures due to FIFO overflow, I didn't notice. It should be fixed now.

2023-01-19 01:18 UTC, mhasself approved these changes
Thanks again.  The current UBC team should have a look but I think this is good to be merged.

2023-07-04 23:57 UTC, merged